# Generated by Django 3.1.5 on 2021-02-04 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='medeical_type',
            new_name='medicine_type',
        ),
    ]
