# Generated by Django 3.1.5 on 2021-02-07 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210204_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'managed': True, 'verbose_name': 'Bill', 'verbose_name_plural': 'Bills'},
        ),
        migrations.AlterModelOptions(
            name='billdetails',
            options={'managed': True, 'verbose_name': 'Billing Details', 'verbose_name_plural': 'Billing Details'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'managed': True, 'verbose_name': 'Company', 'verbose_name_plural': 'Companys'},
        ),
        migrations.AlterModelOptions(
            name='companyacconut',
            options={'managed': True, 'verbose_name': 'Company Account', 'verbose_name_plural': 'Company Account'},
        ),
        migrations.AlterModelOptions(
            name='companybank',
            options={'managed': True, 'verbose_name': 'Company Bank', 'verbose_name_plural': 'Company Bank'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': True, 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='customerrequest',
            options={'managed': True, 'verbose_name': 'Customer Request', 'verbose_name_plural': 'Customer Request'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': True, 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='employeebank',
            options={'managed': True, 'verbose_name': 'Employee Bank', 'verbose_name_plural': 'Employee Bank'},
        ),
        migrations.AlterModelOptions(
            name='employeesalary',
            options={'managed': True, 'verbose_name': 'Employee Salary', 'verbose_name_plural': 'Employee Salaries'},
        ),
        migrations.AlterModelOptions(
            name='medicaldetails',
            options={'managed': True, 'verbose_name': 'Medicine Detail', 'verbose_name_plural': 'Medicine Details'},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'managed': True, 'verbose_name': 'Medicine', 'verbose_name_plural': 'Medicine'},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='joinig_date',
            new_name='joining_date',
        ),
    ]
